"""CLI for the unified synthetic-fidelity evaluation.

Example from the repository root::

    python common_pipeline/02_fidelity/evaluate_fidelity.py

The default final run requires the complete certified registry produced by
phase 01. ``--allow-partial`` exists only for fixture/smoke execution.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import sys
from pathlib import Path

import numpy as np

MODULE_DIR = Path(__file__).resolve().parent
REPOSITORY_ROOT = MODULE_DIR.parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))
if str(MODULE_DIR) not in sys.path:
    sys.path.insert(0, str(MODULE_DIR))

from fidelity_core import (  # noqa: E402
    CHANNEL_ORDER,
    DONOR_TRAIN_COUNT,
    DONOR_VALIDATION_COUNT,
    EVALUATION_SUBSET_SEED,
    EVALUATION_SUBSET_SIZE,
    SYNTHETIC_POOL_COUNT,
    acf_table,
    apply_common_subset,
    c2st_table,
    common_subset_indices,
    correlation_tables,
    joint_tsne_coordinates,
    load_real_reference,
    load_synthetic_pool,
    marginal_statistics,
    nearest_neighbor_table,
    wasserstein_table,
)

contract_registry = importlib.import_module("common_pipeline.01_contract.registry")
DEFAULT_REGISTRY_PATH = (
    REPOSITORY_ROOT / "common_pipeline/01_contract/results/certified_outputs.json"
)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def repository_relative(path: Path, repository_root: Path) -> str:
    return path.resolve().relative_to(repository_root.resolve()).as_posix()


def load_registry_methods(
    registry_path: Path,
    *,
    repository_root: Path,
    allow_partial: bool,
) -> tuple[dict, dict[str, tuple[Path, dict]]]:
    payload = contract_registry.load_certified_registry(registry_path)
    contract_registry.validate_registry_freshness(
        payload,
        repository_root=repository_root,
    )
    selected_payload, _selection = contract_registry.select_experiment_methods(
        payload,
        allow_partial=allow_partial,
    )
    resolved = contract_registry.resolve_certified_paths(
        selected_payload,
        repository_root=repository_root,
    )
    return selected_payload, resolved


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=MODULE_DIR.parents[1],
        help="Repository root (defaults to the root containing common_pipeline)",
    )
    parser.add_argument(
        "--registry-path",
        type=Path,
        default=DEFAULT_REGISTRY_PATH,
        help="Certified output registry generated by 01_contract",
    )
    parser.add_argument(
        "--allow-partial",
        action="store_true",
        help="Smoke/tests only; final runs require four neural methods plus baseline",
    )
    parser.add_argument(
        "--evaluation-subset-seed",
        type=int,
        default=EVALUATION_SUBSET_SEED,
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=MODULE_DIR / "results",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    repository_root = args.repo_root.resolve()
    registry_path = args.registry_path
    if not registry_path.is_absolute():
        registry_path = repository_root / registry_path
    registry_payload, certified = load_registry_methods(
        registry_path.resolve(),
        repository_root=repository_root,
        allow_partial=args.allow_partial,
    )
    for warning in registry_payload["experiment_selection"]["lineage_warnings"]:
        print(f"[WARNING] {warning}")

    donor_train_path = repository_root / "data/features/windows/donor_train.parquet"
    donor_validation_path = (
        repository_root / "data/features/windows/donor_validation.parquet"
    )
    donor_train, real_validation, statistics = load_real_reference(
        donor_train_path, donor_validation_path
    )
    if donor_train.shape[0] != DONOR_TRAIN_COUNT:
        raise RuntimeError("Unexpected donor_train count")
    if real_validation.shape[0] != DONOR_VALIDATION_COUNT:
        raise RuntimeError("Unexpected donor_validation count")

    pools = {
        method: load_synthetic_pool(path, method=method)
        for method, (path, _entry) in sorted(certified.items())
    }

    if any(pool.windows.shape[0] != SYNTHETIC_POOL_COUNT for pool in pools.values()):
        raise RuntimeError("Every common synthetic pool must contain exactly 5000 windows")

    results_dir = args.results_dir.resolve()
    tables_dir = results_dir / "tables"
    tables_dir.mkdir(parents=True, exist_ok=True)

    # One RNG call creates one ordered list of row positions. Reusing this list
    # for every method removes subset-selection noise from model comparisons.
    indices = common_subset_indices(
        evaluation_subset_seed=args.evaluation_subset_seed
    )
    synthetic_subset = apply_common_subset(
        {method: pool.windows for method, pool in pools.items()}, indices
    )
    datasets = {"real": real_validation, **synthetic_subset}

    tables = {
        "marginal_statistics.csv": marginal_statistics(datasets),
        "wasserstein.csv": wasserstein_table(real_validation, synthetic_subset),
        "return_acf.csv": acf_table(
            real_validation, synthetic_subset, absolute=False
        ),
        "abs_return_acf.csv": acf_table(
            real_validation, synthetic_subset, absolute=True
        ),
        "nearest_neighbor.csv": nearest_neighbor_table(
            donor_train, real_validation, synthetic_subset
        ),
        "c2st_results.csv": c2st_table(real_validation, synthetic_subset),
    }
    correlation_values, correlation_errors = correlation_tables(
        real_validation, synthetic_subset
    )
    tables["channel_correlations.csv"] = correlation_values
    tables["correlation_errors.csv"] = correlation_errors
    tables["joint_tsne_coordinates.csv"] = joint_tsne_coordinates(
        real_validation, synthetic_subset
    )
    for filename, table in tables.items():
        table.to_csv(tables_dir / filename, index=False, float_format="%.12g")

    np.savetxt(
        tables_dir / "evaluation_subset_indices.csv",
        indices,
        fmt="%d",
        delimiter=",",
        header="row_position",
        comments="",
    )
    subset_digest = hashlib.sha256(indices.astype("<i8").tobytes()).hexdigest()
    manifest = {
        "run_id": results_dir.name,
        "protocol": "common_normalized_fidelity_v1",
        **registry_payload["experiment_selection"],
        "real_reference": repository_relative(donor_validation_path, repository_root),
        "nearest_neighbor_reference": repository_relative(
            donor_train_path, repository_root
        ),
        "real_count": int(real_validation.shape[0]),
        "real_shape": list(real_validation.shape),
        "synthetic_pool_count": SYNTHETIC_POOL_COUNT,
        "evaluation_subset_size": EVALUATION_SUBSET_SIZE,
        "evaluation_subset_seed": args.evaluation_subset_seed,
        "evaluation_subset_indices_sha256": subset_digest,
        "channel_order": list(CHANNEL_ORDER),
        "space": "global_channel_normalized",
        "normalization": {
            "fit_split": "donor_train",
            "fit_axes": [0, 1],
            "fit_dtype": "float64",
            "output_dtype": "float32",
            "ddof": 0,
            "mean": statistics.mean.tolist(),
            "std": statistics.std.tolist(),
        },
        "synthetic_methods": {
            method: {
                "path": repository_relative(pool.path, repository_root),
                "sha256": sha256_file(pool.path),
                "training_seed": pool.training_seed,
                "space": pool.space,
                "channel_order": list(pool.channel_order),
                "metadata_evidence": pool.metadata_evidence,
                "method_family": certified[method][1]["method_family"],
            }
            for method, pool in pools.items()
        },
        "certified_registry": repository_relative(registry_path, repository_root),
        "certified_registry_sha256": contract_registry.registry_sha256(registry_path),
        "baseline_included": any(
            entry[1]["method_family"] == "simple_baseline"
            for entry in certified.values()
        ),
        "allow_partial": bool(args.allow_partial),
        "physical_sign_validation_applied": False,
        "synthetic_repair_applied": False,
        "tables": sorted(tables),
    }
    (results_dir / "evaluation_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(
        f"Evaluated {len(pools)} methods against {len(real_validation)} real windows; "
        f"tables written to {tables_dir}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
